from utils.contants import CONSTANTS
from utils.config_key_data_constants import CONFIG_KEYS_DATA

config_sdss = {
    CONFIG_KEYS_DATA.ALL_DATA_PATHS: [
        CONSTANTS.DATA_DIR_TRAIN_SDSS_TEMPLATE_LABELED,
        CONSTANTS.DATA_DIR_TEST_SDSS_TEMPLATE_LABELED,
        CONSTANTS.DATA_DIR_VAL_SDSS_TEMPLATE_LABELED,
    ],
    CONFIG_KEYS_DATA.TEMPLATE_SEQUENCE_PATH: CONSTANTS.DATA_DIR_SDSS_TEMPLATE_SEQUENCE,

}
